dist: trusty
pyton:
  - '2.7'
group: deprecated-2017Q4
sudo: required
install:
  - pip install 'urllib3[secure]'
  - sudo pip install -r requirements.txt
  - bundle install
  - apt-get upgrade wget
cache:
  - bundler
  - pip
addons:
  postgresql: '9.6'
script:
  - make clean download import process && ./bin/travis-deploy
